version: '3.8'

services:
  # Solo la aplicación QuickBooks
  quickbooks-app:
    build: .
    container_name: quickbooks-app
    restart: unless-stopped
    ports:
      - "8000:8000"  # Exponer puerto para tu Nginx existente
    environment:
      - FLASK_ENV=production
      - SALES_UPDATE_INTERVAL=1  # Horas entre actualizaciones automáticas
    env_file:
      - .env.production
    volumes:
      - ./data:/app/data      # Persistir base de datos SQLite
      - ./logs:/app/logs      # Persistir logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3